nelmio_api_doc:
    documentation:
        info:
            title: REST API
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:  # Accepts routes under /api except /api/doc
            - ^/api
