version: '3.8'

services:
  nginx:
    container_name: nginx-test
    ports:
      - "127.0.0.2:80:80"
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - systemeio
    depends_on:
      - php
  php:
    container_name: php-fpm-test
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - systemeio

networks:
  systemeio:
