services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../DTO/'

    App\Service\Data\DataProcessor:
        arguments:
            - !tagged_locator { tag: 'app.data_processor' }
    App\Service\Data\DataProvider:
        arguments:
            - !tagged_locator { tag: 'app.data_provider' }

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ '@annotation_reader' ] ]